export const feederConstants = {
    LIST_REQUEST: 'FEEDER_LIST_REQUEST',
    LIST_SUCCESS: 'FEEDER_LIST_SUCCESS',
    LIST_FAILURE: 'FEEDER_LIST_FAILURE',

    SELECT: 'FEEDER_SELECT',
	RESET: 'FEEDER_RESET',
}
